name: 'CodePolicy'
on: ['pull_request']
jobs:
    CodePolicy:
        runs-on: 'ubuntu-latest'
        steps:
            - id: files
              uses: jitterbit/get-changed-files@v1

            - name: 'install dependencies'
              run: sudo apt install -y libcode-tidyall-perl libnamespace-autoclean-perl libxml2-utils
              
            - name: 'checkout otobo'
              uses: actions/checkout@v2

            - name: 'checkout codepolicy'
              uses: actions/checkout@v2
              with:
                repository: RotherOSS/codepolicy
                ref: rel-10_0_3
                path: codepolicy

            - name: 'run CodePolicy'
              run: codepolicy/bin/otobo.CodePolicy.pl -l ${{ steps.files.outputs.added_modified }}

