# adapted from https://raku-advent.blog/2019/12/06/put-some-github-actions-in-your-raku-repositories/
name: 'prove scripts/test/Compile.t'

on: ['push']

jobs:
    syntax_check:
        runs-on: 'ubuntu-latest'


        container:
            # using a working OTOBO images avoids the need to install dependencies
            image: 'rotheross/otobo:devel-rel-10_0'
            options: --user root

        steps:
            # checkout with history
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            # some diagnostics
            - name: perl -V
              run: perl -V
            - name: env
              run: env | sort

            # the setup is just like otobo.web.dockerfile and .dockerignore
            - name: set up Kernel/Config.pm
              run: 'cp --no-clobber Kernel/Config.pm.docker.dist Kernel/Config.pm'
            - name: fix Kernel/Config/Defaults.pm
              run: "perl -pi -e 's/^use lib /# disabled by syntax_check.yml: use lib/' Kernel/Config/Defaults.pm"
            - name: Remove Apache scripts and modules
              run: >
                rm -r
                scripts/apache*
                bin/cgi-bin
                Kernel/cpan-lib/Apache2
                Kernel/System/SupportDataCollector/Plugin/Webserver/Apache

            - name: show changed files
              run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

            # The actual test step.
            # xargs adds the changed files to the prove command
            # :: tells prove that whatever follows should be passed to the test script
            - name: prove
              run: 'git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs prove -I . -I Kernel/cpan-lib -I Custom --verbose scripts/test/Compile.t ::'
